#!/usr/bin/env python
# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Tue Sep 22 15:38:05 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class Main(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Main.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.p_buttons = wx.Panel(self, -1)
        self.p_header = wx.Panel(self, -1)
        self.bm_logo = wx.StaticBitmap(self.p_header, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/main.png", wx.BITMAP_TYPE_ANY))
        self.l_header = wx.StaticText(self.p_header, -1, "JAPOS")
        self.sl_header = wx.StaticLine(self, -1, style=wx.LI_VERTICAL)
        self.bb_opening = wx.BitmapButton(self.p_buttons, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/main/aperturas.png", wx.BITMAP_TYPE_ANY))
        self.bb_sale = wx.BitmapButton(self.p_buttons, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/main/ventas.png", wx.BITMAP_TYPE_ANY))
        self.bb_goods = wx.BitmapButton(self.p_buttons, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/main/productos.png", wx.BITMAP_TYPE_ANY))
        self.bb_cashout = wx.BitmapButton(self.p_buttons, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/main/cortes.png", wx.BITMAP_TYPE_ANY))
        self.bb_cancellation = wx.BitmapButton(self.p_buttons, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/main/cancelaciones.png", wx.BITMAP_TYPE_ANY))
        self.bb_coins = wx.BitmapButton(self.p_buttons, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/main/divisas.png", wx.BITMAP_TYPE_ANY))
        self.bb_switch = wx.BitmapButton(self.p_buttons, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/main/cambiar.png", wx.BITMAP_TYPE_ANY))
        self.static_line_1_copy = wx.StaticLine(self, -1, style=wx.LI_VERTICAL)
        self.bb_exit = wx.BitmapButton(self, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/main/exit.png", wx.BITMAP_TYPE_ANY))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Main.__set_properties
        self.SetTitle("Main")
        self.l_header.SetForegroundColour(wx.Colour(255, 255, 255))
        self.l_header.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.p_header.SetBackgroundColour(wx.Colour(47, 47, 47))
        self.sl_header.SetMinSize((800, 11))
        self.bb_opening.SetSize(self.bb_opening.GetBestSize())
        self.bb_sale.SetSize(self.bb_sale.GetBestSize())
        self.bb_goods.SetSize(self.bb_goods.GetBestSize())
        self.bb_cashout.SetSize(self.bb_cashout.GetBestSize())
        self.bb_cancellation.SetToolTipString("ddsdsds")
        self.bb_cancellation.SetSize(self.bb_cancellation.GetBestSize())
        self.bb_coins.SetSize(self.bb_coins.GetBestSize())
        self.bb_switch.SetSize(self.bb_switch.GetBestSize())
        self.static_line_1_copy.SetMinSize((800, 11))
        self.bb_exit.SetSize(self.bb_exit.GetBestSize())
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Main.__do_layout
        s_main = wx.BoxSizer(wx.VERTICAL)
        gs_buttons = wx.FlexGridSizer(3, 7, 0, 0)
        s_header = wx.BoxSizer(wx.VERTICAL)
        s_header.Add(self.bm_logo, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 10)
        s_header.Add(self.l_header, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.p_header.SetSizer(s_header)
        s_main.Add(self.p_header, 0, wx.EXPAND, 0)
        s_main.Add(self.sl_header, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 5)
        gs_buttons.Add((20, 20), 0, wx.EXPAND, 0)
        gs_buttons.Add(self.bb_opening, 0, wx.ALL, 10)
        gs_buttons.Add((20, 20), 0, wx.EXPAND, 0)
        gs_buttons.Add(self.bb_sale, 0, wx.ALL, 10)
        gs_buttons.Add((20, 20), 0, wx.EXPAND, 0)
        gs_buttons.Add(self.bb_goods, 0, wx.ALL, 10)
        gs_buttons.Add((20, 20), 0, wx.EXPAND, 0)
        gs_buttons.Add((20, 20), 0, wx.EXPAND, 0)
        gs_buttons.Add(self.bb_cashout, 0, wx.ALL, 10)
        gs_buttons.Add((20, 20), 0, wx.EXPAND, 0)
        gs_buttons.Add(self.bb_cancellation, 0, wx.ALL|wx.ALIGN_BOTTOM, 10)
        gs_buttons.Add((20, 20), 0, wx.EXPAND, 0)
        gs_buttons.Add(self.bb_coins, 0, wx.ALL, 10)
        gs_buttons.Add((20, 20), 0, wx.EXPAND, 0)
        gs_buttons.Add((20, 20), 0, wx.EXPAND, 0)
        gs_buttons.Add(self.bb_switch, 0, wx.ALL, 10)
        self.p_buttons.SetSizer(gs_buttons)
        s_main.Add(self.p_buttons, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 50)
        s_main.Add(self.static_line_1_copy, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 5)
        s_main.Add(self.bb_exit, 0, wx.EXPAND|wx.ALIGN_RIGHT, 0)
        self.SetSizer(s_main)
        s_main.Fit(self)
        self.Layout()
        # end wxGlade

# end of class Main


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    f_main = Main(None, -1, "")
    app.SetTopWindow(f_main)
    f_main.Show()
    app.MainLoop()
