#!/usr/bin/env python
# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Tue Sep 22 14:46:48 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class Opening(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Opening.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.p_inputs = wx.Panel(self, -1)
        self.p_header = wx.Panel(self, -1)
        self.l_opening = wx.StaticText(self.p_header, -1, "Apertura")
        self.l_pos = wx.StaticText(self.p_inputs, -1, "Point Of Sale")
        self.cb_pos = wx.ComboBox(self.p_inputs, -1, choices=["terraza", "boutique"], style=wx.CB_DROPDOWN|wx.CB_READONLY)
        self.l_cashier = wx.StaticText(self.p_inputs, -1, "Cashier")
        self.cb_cashier = wx.ComboBox(self.p_inputs, -1, choices=["eeeee", "qqqq"], style=wx.CB_DROPDOWN|wx.CB_READONLY)
        self.l_auditor = wx.StaticText(self.p_inputs, -1, "Auditor")
        self.cb_auditor = wx.ComboBox(self.p_inputs, -1, choices=["fffff", "asasa"], style=wx.CB_DROPDOWN|wx.CB_READONLY)
        self.l_initialfund = wx.StaticText(self.p_inputs, -1, "Initial Fund")
        self.tc_initialfund = wx.TextCtrl(self.p_inputs, -1, "")
        self.b_open = wx.Button(self.p_inputs, wx.ID_OPEN, "")
        self.b_cancel = wx.Button(self.p_inputs, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Opening.__set_properties
        self.SetTitle("Apertura")
        self.l_opening.SetBackgroundColour(wx.Colour(47, 47, 47))
        self.l_opening.SetForegroundColour(wx.Colour(255, 255, 255))
        self.l_opening.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.p_header.SetBackgroundColour(wx.Colour(47, 47, 47))
        self.l_pos.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.cb_pos.SetMinSize((150, 50))
        self.cb_pos.SetFont(wx.Font(40, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.cb_pos.SetSelection(-1)
        self.l_cashier.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.cb_cashier.SetMinSize((150, 50))
        self.cb_cashier.SetSelection(-1)
        self.l_auditor.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.cb_auditor.SetMinSize((150, 50))
        self.cb_auditor.SetSelection(-1)
        self.l_initialfund.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Opening.__do_layout
        s_opening = wx.BoxSizer(wx.VERTICAL)
        gs_inputs = wx.FlexGridSizer(6, 2, 0, 0)
        s_header = wx.BoxSizer(wx.VERTICAL)
        s_header.Add(self.l_opening, 0, wx.ALL|wx.EXPAND, 10)
        self.p_header.SetSizer(s_header)
        s_opening.Add(self.p_header, 0, wx.EXPAND, 0)
        gs_inputs.Add((20, 20), 0, wx.EXPAND, 0)
        gs_inputs.Add((20, 20), 0, wx.EXPAND, 0)
        gs_inputs.Add(self.l_pos, 0, wx.ALL, 5)
        gs_inputs.Add(self.cb_pos, 1, wx.ALL|wx.EXPAND|wx.ALIGN_RIGHT, 5)
        gs_inputs.Add(self.l_cashier, 0, wx.ALL, 5)
        gs_inputs.Add(self.cb_cashier, 1, wx.ALL|wx.EXPAND|wx.ALIGN_RIGHT|wx.ALIGN_CENTER_HORIZONTAL, 5)
        gs_inputs.Add(self.l_auditor, 0, wx.ALL, 5)
        gs_inputs.Add(self.cb_auditor, 0, wx.ALL|wx.EXPAND|wx.ALIGN_RIGHT, 5)
        gs_inputs.Add(self.l_initialfund, 0, wx.ALL, 5)
        gs_inputs.Add(self.tc_initialfund, 0, wx.ALL|wx.EXPAND|wx.ALIGN_RIGHT, 5)
        gs_inputs.Add((20, 20), 0, wx.EXPAND, 0)
        gs_inputs.Add((20, 20), 0, wx.EXPAND, 0)
        gs_inputs.Add(self.b_open, 0, wx.ALIGN_RIGHT, 0)
        gs_inputs.Add(self.b_cancel, 0, wx.ALIGN_RIGHT, 0)
        gs_inputs.Add((20, 20), 0, wx.EXPAND, 0)
        gs_inputs.Add((20, 20), 0, wx.EXPAND, 0)
        self.p_inputs.SetSizer(gs_inputs)
        s_opening.Add(self.p_inputs, 1, wx.ALL|wx.EXPAND, 10)
        self.SetSizer(s_opening)
        s_opening.Fit(self)
        self.Layout()
        # end wxGlade

# end of class Opening


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    dlg_opening = Opening(None, -1, "")
    app.SetTopWindow(dlg_opening)
    dlg_opening.Show()
    app.MainLoop()
