#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun Dec 13 23:20:18 2009

import wx

from controllers.auth import Auth_controller

# begin wxGlade: extracode
# end wxGlade



class Auth_view(wx.Dialog):
    def __init__(self, parent, id):
        # begin wxGlade: Auth_view.__init__
        wx.Dialog.__init__(self, parent, id)
        self.parent = parent
        #print dir(self.parent)
        #self.valid = self.parent.valid
        self.controller_auth = Auth_controller()
        self.l_auth = wx.StaticText(self, -1, "Autorizar", style=wx.ALIGN_CENTRE)
        self.l_auditor = wx.StaticText(self, -1, "Auditor")
        self.cb_username = wx.ComboBox(self, -1, choices=self.controller_auth.choices, style=wx.CB_DROPDOWN|wx.CB_READONLY)
        self.label_2 = wx.StaticText(self, -1, "Password")
        self.tc_password = wx.TextCtrl(self, -1, "", style=wx.TE_PASSWORD)
        self.b_ok = wx.Button(self, wx.ID_OK, "")
        self.b_cancel = wx.Button(self, wx.ID_CANCEL, "")
        self.Center()
        self.Bind(wx.EVT_BUTTON, self.OnAuth, id = self.b_ok.GetId())
        self.Bind(wx.EVT_BUTTON, self.OnCancel, id = self.b_cancel.GetId())

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Auth_view.__set_properties
        self.SetTitle("Autorizar")
        self.l_auth.SetBackgroundColour(wx.Colour(47, 47, 47))
        self.l_auth.SetForegroundColour(wx.Colour(255, 255, 255))
        self.l_auth.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.l_auditor.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.cb_username.SetSelection(-1)
        self.label_2.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Auth_view.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(3, 2, 0, 0)
        sizer_1.Add(self.l_auth, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_1.Add(self.l_auditor, 1, wx.ALL|wx.EXPAND, 10)
        grid_sizer_1.Add(self.cb_username, 0, wx.ALL|wx.EXPAND, 10)
        grid_sizer_1.Add(self.label_2, 0, wx.ALL|wx.EXPAND, 10)
        grid_sizer_1.Add(self.tc_password, 0, wx.ALL|wx.EXPAND, 10)
        grid_sizer_1.Add(self.b_ok, 0, wx.ALL|wx.EXPAND, 10)
        grid_sizer_1.Add(self.b_cancel, 0, wx.ALL|wx.EXPAND, 10)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def OnAuth(self, evt):
	    try:
		    self.username = self.cb_username.GetValue().encode('utf-8')
		    self.password = self.tc_password.GetValue().encode('utf-8')
		    try:
			    self.validate()
		    except:
			    self.controller_auth.error()
	    except:
		    self.controller_auth.error()

    def OnCancel(self, evt):
	    self.Destroy()

    def validate(self):
	    self.parent.valid = self.controller_auth.auth(self.username, self.password)
	    print "valid"
	    print self.parent.valid
	    if self.parent.valid:
		    self.Close()
	    else:
		    self.controller_auth.error()
	    

# end of class Auth_view


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    dlg_auth = Auth_view(None, -1, "")
    app.SetTopWindow(dlg_auth)
    dlg_auth.Show()
    app.MainLoop()
