#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Dec 14 23:31:16 2009

import wx
from controllers.discount import Discount_controller
# begin wxGlade: extracode
# end wxGlade



class Discount_view(wx.Dialog):
    def __init__(self, parent, id):

        wx.Dialog.__init__(self, parent, id)

        self.controller_discount = Discount_controller()

        self.l_discount = wx.StaticText(self, -1, "Descuento", style=wx.ALIGN_CENTRE)
        self.l_type = wx.StaticText(self, -1, "Tipo", style=wx.ALIGN_CENTRE)
        self.cb_type = wx.ComboBox(self, -1, choices=["Descuento de empleado", "Cortesia", "Promocion", "Descuento"], style=wx.CB_DROPDOWN|wx.CB_READONLY)
        self.l_percentage = wx.StaticText(self, -1, "Porcentaje", style=wx.ALIGN_CENTRE)
        self.cb_percentage = wx.ComboBox(self, -1, choices = self.controller_discount.choices, style=wx.CB_DROPDOWN|wx.CB_READONLY)
        self.b_ok = wx.Button(self, wx.ID_OK, "")
        self.b_cancel = wx.Button(self, wx.ID_CANCEL, "")

        self.Center()

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Discount_view.__set_properties
        self.SetTitle("Descuento")
        self.l_discount.SetBackgroundColour(wx.Colour(47, 47, 47))
        self.l_discount.SetForegroundColour(wx.Colour(255, 255, 255))
        self.l_discount.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.cb_type.SetSelection(-1)
        self.cb_percentage.SetSelection(-1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Discount_view.__do_layout
        s_discount = wx.BoxSizer(wx.VERTICAL)
        gs_discount = wx.GridSizer(3, 2, 0, 0)
        s_discount.Add(self.l_discount, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 10)
        gs_discount.Add(self.l_type, 0, wx.ALL|wx.EXPAND, 10)
        gs_discount.Add(self.cb_type, 0, wx.ALL, 10)
        gs_discount.Add(self.l_percentage, 0, wx.ALL|wx.EXPAND, 10)
        gs_discount.Add(self.cb_percentage, 0, wx.ALL, 10)
        gs_discount.Add(self.b_ok, 0, wx.ALL, 10)
        gs_discount.Add(self.b_cancel, 0, wx.ALL, 10)
        s_discount.Add(gs_discount, 1, wx.EXPAND, 0)
        self.SetSizer(s_discount)
        s_discount.Fit(self)
        self.Layout()
        # end wxGlade

# end of class Discount_view


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    dlg_discount = Discount_view(None, -1, "")
    app.SetTopWindow(dlg_discount)
    dlg_discount.Show()
    app.MainLoop()
