#!/usr/bin/env python
# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Sat Dec  5 16:54:09 2009

import wx

from controllers.pay import Pay_controller

# begin wxGlade: extracode
# end wxGlade



class Pay_view(wx.Dialog):
    def __init__(self, parent, id):
        wx.Dialog.__init__(self, parent, id)

        self.controller_pay = Pay_controller()


        self.p_total = wx.Panel(self, -1)
        self.p_due = wx.Panel(self, -1)
        self.p_pay = wx.Panel(self, -1)
        self.bm_cash = wx.BitmapButton(self.p_pay, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/toolbars/coins.png", wx.BITMAP_TYPE_ANY))
        self.bm_card = wx.BitmapButton(self.p_pay, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/toolbars/credit_card.png", wx.BITMAP_TYPE_ANY))
        self.sl_pay = wx.StaticLine(self, -1, style=wx.LI_VERTICAL)

        self.controller_pay.get_data_pay()
        self.cb_salesman = wx.ComboBox(self, -1, choices = self.controller_pay.choices_salesman, style=wx.CB_DROPDOWN|wx.CB_DROPDOWN|wx.CB_READONLY)
        self.cb_coins = wx.ComboBox(self, -1, choices= self.controller_pay.choices_coins, style=wx.CB_DROPDOWN|wx.CB_READONLY)
        self.l_before = wx.StaticText(self, -1, "Antes")
        self.l_vbefore = wx.StaticText(self, -1, "$00.00", style=wx.ALIGN_CENTRE)
        self.l_due = wx.StaticText(self.p_due, -1, "Debe")
        self.l_vdue = wx.StaticText(self.p_due, -1, "$00.00")
        self.tc_total = wx.TextCtrl(self.p_total, -1, "$00.00", style=wx.TE_READONLY)
        self.l_change = wx.StaticText(self.p_total, -1, "Cambio")
        self.l_vchange = wx.StaticText(self.p_total, -1, "$00.00")
        self.b_accept = wx.Button(self, -1, "aceptar")
        self.b_cancel = wx.Button(self, -1, "cancel")
        self.Center()

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Pay_view.__set_properties
        self.SetTitle("Pago")
        self.SetBackgroundColour(wx.Colour(47, 47, 47))
        self.bm_cash.SetSize(self.bm_cash.GetBestSize())
        self.bm_card.SetSize(self.bm_card.GetBestSize())
        self.p_pay.SetBackgroundColour(wx.Colour(47, 47, 47))
        self.sl_pay.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.cb_salesman.SetSelection(-1)
        self.cb_coins.SetSelection(-1)
        self.l_before.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.l_vbefore.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.l_due.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.l_due.SetFont(wx.Font(30, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.l_vdue.SetForegroundColour(wx.Colour(255, 0, 0))
        self.l_vdue.SetFont(wx.Font(25, wx.DECORATIVE, wx.NORMAL, wx.BOLD, 0, ""))
        self.p_due.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.tc_total.SetMinSize((398, 52))
        self.tc_total.SetBackgroundColour(wx.Colour(0, 255, 0))
        self.tc_total.SetFont(wx.Font(40, wx.DECORATIVE, wx.NORMAL, wx.NORMAL, 0, ""))
        self.l_change.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.l_vchange.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.p_total.SetBackgroundColour(wx.Colour(0, 255, 0))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Pay_view.__do_layout
        s_pay = wx.BoxSizer(wx.VERTICAL)
        s_buttons = wx.BoxSizer(wx.HORIZONTAL)
        s_total = wx.BoxSizer(wx.VERTICAL)
        s_due = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        s_paymentforms = wx.BoxSizer(wx.HORIZONTAL)
        s_paymentforms.Add(self.bm_cash, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 10)
        s_paymentforms.Add(self.bm_card, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 10)
        self.p_pay.SetSizer(s_paymentforms)
        s_pay.Add(self.p_pay, 0, wx.EXPAND, 0)
        s_pay.Add(self.sl_pay, 0, wx.ALL|wx.EXPAND, 10)
        sizer_5.Add(self.cb_salesman, 0, wx.ALL, 10)
        sizer_5.Add(self.cb_coins, 0, wx.ALL, 10)
        sizer_5.Add(self.l_before, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5)
        sizer_5.Add(self.l_vbefore, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5)
        s_pay.Add(sizer_5, 0, wx.EXPAND, 0)
        s_due.Add(self.l_due, 0, wx.ALIGN_CENTER_HORIZONTAL, 10)
        s_due.Add(self.l_vdue, 0, wx.ALIGN_CENTER_HORIZONTAL, 10)
        self.p_due.SetSizer(s_due)
        s_pay.Add(self.p_due, 0, wx.EXPAND, 0)
        s_total.Add(self.tc_total, 0, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL, 10)
        s_total.Add(self.l_change, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5)
        s_total.Add(self.l_vchange, 0, wx.LEFT|wx.RIGHT|wx.ALIGN_CENTER_HORIZONTAL, 5)
        self.p_total.SetSizer(s_total)
        s_pay.Add(self.p_total, 0, wx.EXPAND, 0)
        s_buttons.Add(self.b_accept, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 10)
        s_buttons.Add(self.b_cancel, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 10)
        s_pay.Add(s_buttons, 0, wx.EXPAND, 0)
        self.SetSizer(s_pay)
        s_pay.Fit(self)
        self.Layout()
        # end wxGlade

# end of class Pay_view


class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # content of this block not found: did you rename this class?
        pass

    def __set_properties(self):
        # content of this block not found: did you rename this class?
        pass

    def __do_layout(self):
        # content of this block not found: did you rename this class?
        pass

# end of class MyDialog


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    dlg_pay = MyDialog(None, -1, "")
    app.SetTopWindow(dlg_pay)
    dlg_pay.Show()
    app.MainLoop()
