#!/usr/bin/env python
# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Sun Sep 27 18:58:23 2009

import wx

from views.salesList import SalesList_view
# begin wxGlade: extracode
# end wxGlade



class RightPanel_view(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: RightPanel_view.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.p_maintoolbar = wx.Panel(self, -1, style=wx.SIMPLE_BORDER|wx.TAB_TRAVERSAL)
        self.bm_opening = wx.BitmapButton(self.p_maintoolbar, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/toolbars/opening.png", wx.BITMAP_TYPE_ANY))
        self.sl_1 = wx.StaticLine(self.p_maintoolbar, -1)
        self.tc_searchsale = wx.TextCtrl(self.p_maintoolbar, -1, "")
        self.bm_addsale = wx.BitmapButton(self.p_maintoolbar, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/toolbars/add.png", wx.BITMAP_TYPE_ANY))
        self.sl_2 = wx.StaticLine(self.p_maintoolbar, -1)
        self.bm_cancel = wx.BitmapButton(self.p_maintoolbar, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/toolbars/cancellation.png", wx.BITMAP_TYPE_ANY))
        self.p_content = SalesList_view(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: RightPanel_view.__set_properties
        self.bm_opening.SetSize(self.bm_opening.GetBestSize())
        self.sl_1.SetMinSize((1, 70))
        self.tc_searchsale.SetMinSize((450, 30))
        self.bm_addsale.SetSize(self.bm_addsale.GetBestSize())
        self.sl_2.SetMinSize((1, 70))
        self.bm_cancel.SetSize(self.bm_cancel.GetBestSize())
        self.p_maintoolbar.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_WINDOWFRAME))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: RightPanel_view.__do_layout
        s_right = wx.BoxSizer(wx.VERTICAL)
        s_maintoolbar = wx.FlexGridSizer(1, 6, 0, 0)
        s_maintoolbar.Add(self.bm_opening, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 10)
        s_maintoolbar.Add(self.sl_1, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 10)
        s_maintoolbar.Add(self.tc_searchsale, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 10)
        s_maintoolbar.Add(self.bm_addsale, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 10)
        s_maintoolbar.Add(self.sl_2, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 10)
        s_maintoolbar.Add(self.bm_cancel, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 10)
        self.p_maintoolbar.SetSizer(s_maintoolbar)
        s_maintoolbar.AddGrowableRow(0)
        s_maintoolbar.AddGrowableCol(1)
        s_maintoolbar.AddGrowableCol(2)
        s_maintoolbar.AddGrowableCol(3)
        s_right.Add(self.p_maintoolbar, 0, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL, 0)
        s_right.Add(self.p_content, 1, wx.EXPAND, 10)
        self.SetSizer(s_right)
        s_right.Fit(self)
        # end wxGlade

# end of class RightPanel_view


class MainToolBar(wx.ToolBar):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainToolBar.__init__
        kwds["style"] = wx.TB_DOCKABLE|wx.TB_3DBUTTONS|wx.TB_TEXT
        wx.ToolBar.__init__(self, *args, **kwds)
        self.AddLabelTool(wx.NewId(), "Abrir turno", wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/toolbars/opening.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.AddSeparator()
        self.AddLabelTool(wx.NewId(), "buscar venta", wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/toolbars/opening.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.AddSeparator()
        self.AddLabelTool(wx.NewId(), "Nueva venta", wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/toolbars/add.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.AddLabelTool(wx.NewId(), "Cancelar", wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/toolbars/cancellation.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainToolBar.__set_properties
        self.SetMargins((0, 0))
        self.Realize()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainToolBar.__do_layout
        pass
        # end wxGlade

# end of class MainToolBar


