#!/usr/bin/env python
# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Sat Sep 26 16:42:10 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class RightPanelView(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: RightPanelView.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.panel_4 = wx.Panel(self, -1, style=wx.SIMPLE_BORDER|wx.TAB_TRAVERSAL)
        self.panel_5 = wx.Panel(self, -1)
        self.panel_4_copy = wx.Panel(self, -1, style=wx.SIMPLE_BORDER|wx.TAB_TRAVERSAL)
        self.bitmap_button_2_copy = wx.BitmapButton(self.panel_4_copy, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/toolbars/opening.png", wx.BITMAP_TYPE_ANY))
        self.static_line_1_copy_2 = wx.StaticLine(self.panel_4_copy, -1)
        self.text_ctrl_2_copy = wx.TextCtrl(self.panel_4_copy, -1, "")
        self.bitmap_button_3_copy = wx.BitmapButton(self.panel_4_copy, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/toolbars/add.png", wx.BITMAP_TYPE_ANY))
        self.static_line_1_copy_1_copy = wx.StaticLine(self.panel_4_copy, -1)
        self.bitmap_button_4_copy = wx.BitmapButton(self.panel_4_copy, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/toolbars/cancellation.png", wx.BITMAP_TYPE_ANY))
        self.label_3 = wx.StaticText(self, -1, "Venta 2009-22")
        self.list_ctrl_1 = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.label_18 = wx.StaticText(self.panel_5, -1, "Subtotal:")
        self.label_19 = wx.StaticText(self.panel_5, -1, "Impuesto:")
        self.label_20 = wx.StaticText(self.panel_5, -1, "Total:")
        self.label_21 = wx.StaticText(self.panel_5, -1, "0.000")
        self.label_22 = wx.StaticText(self.panel_5, -1, "0.000")
        self.label_23 = wx.StaticText(self.panel_5, -1, "0.000")
        self.bitmap_button_2 = wx.BitmapButton(self.panel_4, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/toolbars/exit.png", wx.BITMAP_TYPE_ANY))
        self.static_line_1 = wx.StaticLine(self.panel_4, -1)
        self.text_ctrl_2 = wx.TextCtrl(self.panel_4, -1, "")
        self.bitmap_button_3 = wx.BitmapButton(self.panel_4, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/toolbars/delete.png", wx.BITMAP_TYPE_ANY))
        self.static_line_1_copy_1 = wx.StaticLine(self.panel_4, -1)
        self.bitmap_button_4 = wx.BitmapButton(self.panel_4, -1, wx.Bitmap("/Users/jyr/Desarrollo/git-projects/japos-client/img/toolbars/pay.png", wx.BITMAP_TYPE_ANY))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: RightPanelView.__set_properties
        self.bitmap_button_2_copy.SetSize(self.bitmap_button_2_copy.GetBestSize())
        self.static_line_1_copy_2.SetMinSize((1, 70))
        self.text_ctrl_2_copy.SetMinSize((450, 30))
        self.bitmap_button_3_copy.SetSize(self.bitmap_button_3_copy.GetBestSize())
        self.static_line_1_copy_1_copy.SetMinSize((1, 70))
        self.bitmap_button_4_copy.SetSize(self.bitmap_button_4_copy.GetBestSize())
        self.panel_4_copy.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_WINDOWFRAME))
        self.label_3.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_18.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.label_19.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Lucida Grande"))
        self.label_20.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_23.SetFont(wx.Font(25, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.bitmap_button_2.SetSize(self.bitmap_button_2.GetBestSize())
        self.static_line_1.SetMinSize((1, 70))
        self.text_ctrl_2.SetMinSize((450, 30))
        self.bitmap_button_3.SetSize(self.bitmap_button_3.GetBestSize())
        self.static_line_1_copy_1.SetMinSize((1, 70))
        self.bitmap_button_4.SetSize(self.bitmap_button_4.GetBestSize())
        self.panel_4.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_WINDOWFRAME))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: RightPanelView.__do_layout
        s_right = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.FlexGridSizer(1, 6, 0, 0)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_7_copy = wx.FlexGridSizer(1, 6, 0, 0)
        sizer_7_copy.Add(self.bitmap_button_2_copy, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 10)
        sizer_7_copy.Add(self.static_line_1_copy_2, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 10)
        sizer_7_copy.Add(self.text_ctrl_2_copy, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 10)
        sizer_7_copy.Add(self.bitmap_button_3_copy, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 10)
        sizer_7_copy.Add(self.static_line_1_copy_1_copy, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 10)
        sizer_7_copy.Add(self.bitmap_button_4_copy, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 10)
        self.panel_4_copy.SetSizer(sizer_7_copy)
        sizer_7_copy.AddGrowableRow(0)
        sizer_7_copy.AddGrowableCol(1)
        sizer_7_copy.AddGrowableCol(2)
        sizer_7_copy.AddGrowableCol(3)
        s_right.Add(self.panel_4_copy, 0, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL, 0)
        s_right.Add(self.label_3, 0, wx.ALL, 10)
        s_right.Add(self.list_ctrl_1, 1, wx.EXPAND, 0)
        sizer_9.Add(self.label_18, 0, wx.ALIGN_RIGHT, 0)
        sizer_9.Add(self.label_19, 0, wx.ALIGN_RIGHT, 0)
        sizer_9.Add(self.label_20, 0, wx.ALIGN_RIGHT, 0)
        sizer_8.Add(sizer_9, 1, 0, 0)
        sizer_10.Add(self.label_21, 0, wx.ALIGN_RIGHT, 0)
        sizer_10.Add(self.label_22, 0, wx.ALIGN_RIGHT, 0)
        sizer_10.Add(self.label_23, 0, wx.ALIGN_RIGHT, 0)
        sizer_8.Add(sizer_10, 1, wx.EXPAND, 0)
        self.panel_5.SetSizer(sizer_8)
        s_right.Add(self.panel_5, 0, wx.ALL|wx.EXPAND, 10)
        sizer_7.Add(self.bitmap_button_2, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 10)
        sizer_7.Add(self.static_line_1, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 10)
        sizer_7.Add(self.text_ctrl_2, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 10)
        sizer_7.Add(self.bitmap_button_3, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 10)
        sizer_7.Add(self.static_line_1_copy_1, 1, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 10)
        sizer_7.Add(self.bitmap_button_4, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 10)
        self.panel_4.SetSizer(sizer_7)
        sizer_7.AddGrowableRow(0)
        sizer_7.AddGrowableCol(1)
        sizer_7.AddGrowableCol(2)
        sizer_7.AddGrowableCol(3)
        s_right.Add(self.panel_4, 0, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.SetSizer(s_right)
        s_right.Fit(self)
        # end wxGlade

# end of class RightPanelView


