#!/usr/bin/env python
# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Sun Sep 27 17:16:00 2009

import wx
from controllers.salesList import SalesList

# begin wxGlade: extracode
# end wxGlade



class SalesList_view(wx.Panel):
    def __init__(self, parent, id):
        # begin wxGlade: SalesList_view.__init__
        self.parent = parent
        self.list_sales_current = self.parent.list_sales_current
        wx.Panel.__init__(self, parent, id)
        
        self.controller = SalesList()
        self.controller.get_sales()
        self.controller.get_total_products()
        self.controller.get_total_all()
                
        self.l_venta = wx.StaticText(self, -1, "Ventas")
        self.lc_saleslist = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER)
        self.lc_saleslist.InsertColumn(0,'') 
        self.lc_saleslist.InsertColumn(1,'id')
        self.lc_saleslist.InsertColumn(2,'SKU')
        self.lc_saleslist.InsertColumn(3,'Venta')
        self.lc_saleslist.InsertColumn(4,'Productos')
        self.lc_saleslist.InsertColumn(5,'Total')
        self.lc_saleslist.SetColumnWidth(0, 50)
        self.lc_saleslist.SetColumnWidth(1, 50)
        self.lc_saleslist.SetColumnWidth(2, 130)
        self.lc_saleslist.SetColumnWidth(3, 210)
        self.lc_saleslist.SetColumnWidth(4, 100)
        self.lc_saleslist.SetColumnWidth(5, 200)
        
        self.list_sales()
        
        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SalesList_view.__set_properties
        self.l_venta.SetFont(wx.Font(20, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SalesList_view.__do_layout
        s_saleslist = wx.BoxSizer(wx.VERTICAL)
        s_saleslist.Add(self.l_venta, 0, wx.ALL, 10)
        s_saleslist.Add(self.lc_saleslist, 1, wx.EXPAND, 10)
        self.SetSizer(s_saleslist)
        s_saleslist.Fit(self)
        # end wxGlade

    def list_sales(self):
	    """
	    Obtiene la lista de ventas por pos al iniciar el turno
	    y crea la lista que guardara la lista de ventas actuales
	    """
	    if not self.list_sales_current:
		    for i in range(0, len(self.controller.sales)):
			    self.list_sales_current.append({'id': i+1,'sku': unicode(self.controller.sales[i][1]), 'sale': unicode(self.controller.sales[i][2]), 'amount': unicode(self.controller.total_products[i]['amount__sum']), 'total':unicode(self.controller.total[i]), 'products': []})

		    for item in self.list_sales_current:
			    index = self.lc_saleslist.InsertStringItem(0, '')
			    self.lc_saleslist.SetStringItem(index,1, unicode(item['id']))
			    self.lc_saleslist.SetStringItem(index,2, unicode(item['sku']))
			    self.lc_saleslist.SetStringItem(index,3, unicode(item['sale']))
			    self.lc_saleslist.SetStringItem(index,4, unicode(item['amount']))
			    self.lc_saleslist.SetStringItem(index,5, unicode(item['total']))

# end of class SalesList_view


